const fs = require('fs');
const path = require('path');

const translationsDir = path.join(__dirname, '..', 'translations');

// Category name translations for sidebar "ALL CATEGORIES" section
// These map English category names to translated versions
const langData = {
  ar: {
    "title_site_info": "معلومات الموقع",
    "cat_Aesthetic": "جمالي", "cat_Animal": "حيوانات", "cat_Arrow": "أسهم", "cat_Award": "جوائز",
    "cat_Border": "حدود", "cat_Bracket": "أقواس", "cat_Bubble": "فقاعات", "cat_Card": "بطاقات",
    "cat_Checkmark": "علامات", "cat_Chess": "شطرنج", "cat_Chinese": "صيني", "cat_Circle": "دائرة",
    "cat_Comparison": "مقارنة", "cat_Copyright": "حقوق النشر", "cat_Corner": "زوايا",
    "cat_Cross": "صليب", "cat_Crown": "تاج", "cat_Crypto": "عملات رقمية", "cat_Currency": "عملات",
    "cat_Cursive": "خط متصل", "cat_Diamond": "ألماس", "cat_Dice": "نرد", "cat_Divider": "فواصل",
    "cat_Dot": "نقاط", "cat_Down Arrow": "سهم لأسفل", "cat_Emoji Faces": "وجوه إيموجي",
    "cat_Flower": "زهور", "cat_Fraction": "كسور", "cat_Gender": "جنس", "cat_German": "ألماني",
    "cat_Greek": "يوناني", "cat_Hand": "يد", "cat_Heart": "قلب", "cat_House": "منزل",
    "cat_Infinity": "لا نهاية", "cat_Japanese": "ياباني", "cat_Korean": "كوري", "cat_Line": "خط",
    "cat_Loading": "تحميل", "cat_Lock": "قفل", "cat_Math": "رياضيات", "cat_Medal": "ميدالية",
    "cat_Medical": "طبي", "cat_Moon": "قمر", "cat_Music": "موسيقى", "cat_Numbers": "أرقام",
    "cat_Office": "مكتب", "cat_Old English": "إنجليزي قديم", "cat_Punctuation": "علامات ترقيم",
    "cat_Quotation": "اقتباسات", "cat_Rectangle": "مستطيل", "cat_Religion": "دين",
    "cat_Roman Numerals": "أرقام رومانية", "cat_Sparkle": "لمعان", "cat_Square": "مربع",
    "cat_Star": "نجمة", "cat_Sun": "شمس", "cat_Transport": "نقل", "cat_Triangle": "مثلث",
    "cat_Unit": "وحدات", "cat_Up Arrow": "سهم لأعلى", "cat_Upside Down": "مقلوب",
    "cat_Warning": "تحذير", "cat_Wave": "موجة", "cat_Weapon": "أسلحة", "cat_Weather": "طقس",
    "cat_Writing": "كتابة", "cat_Zodiac": "أبراج"
  },
  bg: {
    "title_site_info": "ИНФОРМАЦИЯ ЗА САЙТА",
    "cat_Aesthetic": "Естетични", "cat_Animal": "Животни", "cat_Arrow": "Стрелки", "cat_Award": "Награди",
    "cat_Border": "Рамки", "cat_Bracket": "Скоби", "cat_Bubble": "Мехурчета", "cat_Card": "Карти",
    "cat_Checkmark": "Отметки", "cat_Chess": "Шах", "cat_Chinese": "Китайски", "cat_Circle": "Кръг",
    "cat_Comparison": "Сравнение", "cat_Copyright": "Авторски права", "cat_Corner": "Ъгли",
    "cat_Cross": "Кръст", "cat_Crown": "Корона", "cat_Crypto": "Крипто", "cat_Currency": "Валути",
    "cat_Cursive": "Ръкопис", "cat_Diamond": "Диамант", "cat_Dice": "Зарове", "cat_Divider": "Разделители",
    "cat_Dot": "Точки", "cat_Down Arrow": "Стрелка надолу", "cat_Emoji Faces": "Емоджи Лица",
    "cat_Flower": "Цвете", "cat_Fraction": "Дроби", "cat_Gender": "Пол", "cat_German": "Немски",
    "cat_Greek": "Гръцки", "cat_Hand": "Ръка", "cat_Heart": "Сърце", "cat_House": "Къща",
    "cat_Infinity": "Безкрайност", "cat_Japanese": "Японски", "cat_Korean": "Корейски", "cat_Line": "Линия",
    "cat_Loading": "Зареждане", "cat_Lock": "Ключалка", "cat_Math": "Математика", "cat_Medal": "Медал",
    "cat_Medical": "Медицински", "cat_Moon": "Луна", "cat_Music": "Музика", "cat_Numbers": "Числа",
    "cat_Office": "Офис", "cat_Old English": "Стар Английски", "cat_Punctuation": "Пунктуация",
    "cat_Quotation": "Кавички", "cat_Rectangle": "Правоъгълник", "cat_Religion": "Религия",
    "cat_Roman Numerals": "Римски Цифри", "cat_Sparkle": "Блясък", "cat_Square": "Квадрат",
    "cat_Star": "Звезда", "cat_Sun": "Слънце", "cat_Transport": "Транспорт", "cat_Triangle": "Триъгълник",
    "cat_Unit": "Единици", "cat_Up Arrow": "Стрелка нагоре", "cat_Upside Down": "Обърнат",
    "cat_Warning": "Предупреждение", "cat_Wave": "Вълна", "cat_Weapon": "Оръжие", "cat_Weather": "Време",
    "cat_Writing": "Писане", "cat_Zodiac": "Зодиак"
  },
  bn: {
    "title_site_info": "সাইট তথ্য",
    "cat_Aesthetic": "নান্দনিক", "cat_Animal": "পশু", "cat_Arrow": "তীর", "cat_Award": "পুরস্কার",
    "cat_Border": "বর্ডার", "cat_Bracket": "বন্ধনী", "cat_Bubble": "বাবল", "cat_Card": "কার্ড",
    "cat_Checkmark": "টিক", "cat_Chess": "দাবা", "cat_Chinese": "চীনা", "cat_Circle": "বৃত্ত",
    "cat_Comparison": "তুলনা", "cat_Copyright": "কপিরাইট", "cat_Corner": "কোণ",
    "cat_Cross": "ক্রস", "cat_Crown": "মুকুট", "cat_Crypto": "ক্রিপ্টো", "cat_Currency": "মুদ্রা",
    "cat_Cursive": "কার্সিভ", "cat_Diamond": "হীরা", "cat_Dice": "ছক্কা", "cat_Divider": "বিভাজক",
    "cat_Dot": "বিন্দু", "cat_Down Arrow": "নিচের তীর", "cat_Emoji Faces": "ইমোজি মুখ",
    "cat_Flower": "ফুল", "cat_Fraction": "ভগ্নাংশ", "cat_Gender": "লিঙ্গ", "cat_German": "জার্মান",
    "cat_Greek": "গ্রীক", "cat_Hand": "হাত", "cat_Heart": "হৃদয়", "cat_House": "ঘর",
    "cat_Infinity": "অসীম", "cat_Japanese": "জাপানি", "cat_Korean": "কোরিয়ান", "cat_Line": "রেখা",
    "cat_Loading": "লোডিং", "cat_Lock": "তালা", "cat_Math": "গণিত", "cat_Medal": "পদক",
    "cat_Medical": "চিকিৎসা", "cat_Moon": "চাঁদ", "cat_Music": "সঙ্গীত", "cat_Numbers": "সংখ্যা",
    "cat_Office": "অফিস", "cat_Old English": "পুরাতন ইংরেজি", "cat_Punctuation": "বিরাম চিহ্ন",
    "cat_Quotation": "উদ্ধৃতি", "cat_Rectangle": "আয়তক্ষেত্র", "cat_Religion": "ধর্ম",
    "cat_Roman Numerals": "রোমান সংখ্যা", "cat_Sparkle": "ঝিকিমিকি", "cat_Square": "বর্গ",
    "cat_Star": "তারা", "cat_Sun": "সূর্য", "cat_Transport": "পরিবহন", "cat_Triangle": "ত্রিভুজ",
    "cat_Unit": "একক", "cat_Up Arrow": "উপরের তীর", "cat_Upside Down": "উল্টো",
    "cat_Warning": "সতর্কতা", "cat_Wave": "তরঙ্গ", "cat_Weapon": "অস্ত্র", "cat_Weather": "আবহাওয়া",
    "cat_Writing": "লেখা", "cat_Zodiac": "রাশি"
  },
  de: {
    "title_site_info": "SEITENINFO",
    "cat_Aesthetic": "Ästhetisch", "cat_Animal": "Tiere", "cat_Arrow": "Pfeile", "cat_Award": "Auszeichnungen",
    "cat_Border": "Rahmen", "cat_Bracket": "Klammern", "cat_Bubble": "Blasen", "cat_Card": "Karten",
    "cat_Checkmark": "Häkchen", "cat_Chess": "Schach", "cat_Chinese": "Chinesisch", "cat_Circle": "Kreis",
    "cat_Comparison": "Vergleich", "cat_Copyright": "Urheberrecht", "cat_Corner": "Ecken",
    "cat_Cross": "Kreuz", "cat_Crown": "Krone", "cat_Crypto": "Krypto", "cat_Currency": "Währung",
    "cat_Cursive": "Kursiv", "cat_Diamond": "Diamant", "cat_Dice": "Würfel", "cat_Divider": "Trennzeichen",
    "cat_Dot": "Punkte", "cat_Down Arrow": "Pfeil nach unten", "cat_Emoji Faces": "Emoji-Gesichter",
    "cat_Flower": "Blumen", "cat_Fraction": "Brüche", "cat_Gender": "Geschlecht", "cat_German": "Deutsch",
    "cat_Greek": "Griechisch", "cat_Hand": "Hand", "cat_Heart": "Herz", "cat_House": "Haus",
    "cat_Infinity": "Unendlich", "cat_Japanese": "Japanisch", "cat_Korean": "Koreanisch", "cat_Line": "Linie",
    "cat_Loading": "Laden", "cat_Lock": "Schloss", "cat_Math": "Mathe", "cat_Medal": "Medaille",
    "cat_Medical": "Medizin", "cat_Moon": "Mond", "cat_Music": "Musik", "cat_Numbers": "Zahlen",
    "cat_Office": "Büro", "cat_Old English": "Altenglisch", "cat_Punctuation": "Satzzeichen",
    "cat_Quotation": "Anführungszeichen", "cat_Rectangle": "Rechteck", "cat_Religion": "Religion",
    "cat_Roman Numerals": "Römische Zahlen", "cat_Sparkle": "Funkeln", "cat_Square": "Quadrat",
    "cat_Star": "Stern", "cat_Sun": "Sonne", "cat_Transport": "Transport", "cat_Triangle": "Dreieck",
    "cat_Unit": "Einheiten", "cat_Up Arrow": "Pfeil nach oben", "cat_Upside Down": "Umgedreht",
    "cat_Warning": "Warnung", "cat_Wave": "Welle", "cat_Weapon": "Waffen", "cat_Weather": "Wetter",
    "cat_Writing": "Schreiben", "cat_Zodiac": "Sternzeichen"
  },
  es: {
    "title_site_info": "INFORMACIÓN DEL SITIO",
    "cat_Aesthetic": "Estético", "cat_Animal": "Animales", "cat_Arrow": "Flechas", "cat_Award": "Premios",
    "cat_Border": "Bordes", "cat_Bracket": "Corchetes", "cat_Bubble": "Burbujas", "cat_Card": "Cartas",
    "cat_Checkmark": "Marcas", "cat_Chess": "Ajedrez", "cat_Chinese": "Chino", "cat_Circle": "Círculo",
    "cat_Comparison": "Comparación", "cat_Copyright": "Derechos", "cat_Corner": "Esquinas",
    "cat_Cross": "Cruz", "cat_Crown": "Corona", "cat_Crypto": "Cripto", "cat_Currency": "Moneda",
    "cat_Cursive": "Cursiva", "cat_Diamond": "Diamante", "cat_Dice": "Dados", "cat_Divider": "Divisores",
    "cat_Dot": "Puntos", "cat_Down Arrow": "Flecha abajo", "cat_Emoji Faces": "Caras Emoji",
    "cat_Flower": "Flores", "cat_Fraction": "Fracciones", "cat_Gender": "Género", "cat_German": "Alemán",
    "cat_Greek": "Griego", "cat_Hand": "Mano", "cat_Heart": "Corazón", "cat_House": "Casa",
    "cat_Infinity": "Infinito", "cat_Japanese": "Japonés", "cat_Korean": "Coreano", "cat_Line": "Línea",
    "cat_Loading": "Cargando", "cat_Lock": "Candado", "cat_Math": "Matemáticas", "cat_Medal": "Medalla",
    "cat_Medical": "Médico", "cat_Moon": "Luna", "cat_Music": "Música", "cat_Numbers": "Números",
    "cat_Office": "Oficina", "cat_Old English": "Inglés Antiguo", "cat_Punctuation": "Puntuación",
    "cat_Quotation": "Comillas", "cat_Rectangle": "Rectángulo", "cat_Religion": "Religión",
    "cat_Roman Numerals": "Números Romanos", "cat_Sparkle": "Brillo", "cat_Square": "Cuadrado",
    "cat_Star": "Estrella", "cat_Sun": "Sol", "cat_Transport": "Transporte", "cat_Triangle": "Triángulo",
    "cat_Unit": "Unidades", "cat_Up Arrow": "Flecha arriba", "cat_Upside Down": "Al revés",
    "cat_Warning": "Advertencia", "cat_Wave": "Ola", "cat_Weapon": "Armas", "cat_Weather": "Clima",
    "cat_Writing": "Escritura", "cat_Zodiac": "Zodiaco"
  },
  fr: {
    "title_site_info": "INFOS DU SITE",
    "cat_Aesthetic": "Esthétique", "cat_Animal": "Animaux", "cat_Arrow": "Flèches", "cat_Award": "Récompenses",
    "cat_Border": "Bordures", "cat_Bracket": "Crochets", "cat_Bubble": "Bulles", "cat_Card": "Cartes",
    "cat_Checkmark": "Coches", "cat_Chess": "Échecs", "cat_Chinese": "Chinois", "cat_Circle": "Cercle",
    "cat_Comparison": "Comparaison", "cat_Copyright": "Droits d'auteur", "cat_Corner": "Coins",
    "cat_Cross": "Croix", "cat_Crown": "Couronne", "cat_Crypto": "Crypto", "cat_Currency": "Devises",
    "cat_Cursive": "Cursif", "cat_Diamond": "Diamant", "cat_Dice": "Dés", "cat_Divider": "Séparateurs",
    "cat_Dot": "Points", "cat_Down Arrow": "Flèche bas", "cat_Emoji Faces": "Visages Emoji",
    "cat_Flower": "Fleurs", "cat_Fraction": "Fractions", "cat_Gender": "Genre", "cat_German": "Allemand",
    "cat_Greek": "Grec", "cat_Hand": "Main", "cat_Heart": "Cœur", "cat_House": "Maison",
    "cat_Infinity": "Infini", "cat_Japanese": "Japonais", "cat_Korean": "Coréen", "cat_Line": "Ligne",
    "cat_Loading": "Chargement", "cat_Lock": "Cadenas", "cat_Math": "Maths", "cat_Medal": "Médaille",
    "cat_Medical": "Médical", "cat_Moon": "Lune", "cat_Music": "Musique", "cat_Numbers": "Nombres",
    "cat_Office": "Bureau", "cat_Old English": "Vieil Anglais", "cat_Punctuation": "Ponctuation",
    "cat_Quotation": "Guillemets", "cat_Rectangle": "Rectangle", "cat_Religion": "Religion",
    "cat_Roman Numerals": "Chiffres Romains", "cat_Sparkle": "Éclat", "cat_Square": "Carré",
    "cat_Star": "Étoile", "cat_Sun": "Soleil", "cat_Transport": "Transport", "cat_Triangle": "Triangle",
    "cat_Unit": "Unités", "cat_Up Arrow": "Flèche haut", "cat_Upside Down": "À l'envers",
    "cat_Warning": "Avertissement", "cat_Wave": "Vague", "cat_Weapon": "Armes", "cat_Weather": "Météo",
    "cat_Writing": "Écriture", "cat_Zodiac": "Zodiaque"
  },
  hi: {
    "title_site_info": "साइट जानकारी",
    "cat_Aesthetic": "सौंदर्य", "cat_Animal": "जानवर", "cat_Arrow": "तीर", "cat_Award": "पुरस्कार",
    "cat_Border": "बॉर्डर", "cat_Bracket": "ब्रैकेट", "cat_Bubble": "बबल", "cat_Card": "कार्ड",
    "cat_Checkmark": "टिक", "cat_Chess": "शतरंज", "cat_Chinese": "चीनी", "cat_Circle": "वृत्त",
    "cat_Comparison": "तुलना", "cat_Copyright": "कॉपीराइट", "cat_Corner": "कोना",
    "cat_Cross": "क्रॉस", "cat_Crown": "मुकुट", "cat_Crypto": "क्रिप्टो", "cat_Currency": "मुद्रा",
    "cat_Cursive": "कर्सिव", "cat_Diamond": "हीरा", "cat_Dice": "पासा", "cat_Divider": "विभाजक",
    "cat_Dot": "बिंदु", "cat_Down Arrow": "नीचे तीर", "cat_Emoji Faces": "इमोजी चेहरे",
    "cat_Flower": "फूल", "cat_Fraction": "भिन्न", "cat_Gender": "लिंग", "cat_German": "जर्मन",
    "cat_Greek": "ग्रीक", "cat_Hand": "हाथ", "cat_Heart": "दिल", "cat_House": "घर",
    "cat_Infinity": "अनंत", "cat_Japanese": "जापानी", "cat_Korean": "कोरियाई", "cat_Line": "रेखा",
    "cat_Loading": "लोडिंग", "cat_Lock": "ताला", "cat_Math": "गणित", "cat_Medal": "पदक",
    "cat_Medical": "चिकित्सा", "cat_Moon": "चाँद", "cat_Music": "संगीत", "cat_Numbers": "अंक",
    "cat_Office": "कार्यालय", "cat_Old English": "पुरानी अंग्रेज़ी", "cat_Punctuation": "विराम चिह्न",
    "cat_Quotation": "उद्धरण", "cat_Rectangle": "आयत", "cat_Religion": "धर्म",
    "cat_Roman Numerals": "रोमन अंक", "cat_Sparkle": "चमक", "cat_Square": "वर्ग",
    "cat_Star": "तारा", "cat_Sun": "सूर्य", "cat_Transport": "परिवहन", "cat_Triangle": "त्रिकोण",
    "cat_Unit": "इकाई", "cat_Up Arrow": "ऊपर तीर", "cat_Upside Down": "उल्टा",
    "cat_Warning": "चेतावनी", "cat_Wave": "लहर", "cat_Weapon": "हथियार", "cat_Weather": "मौसम",
    "cat_Writing": "लेखन", "cat_Zodiac": "राशि"
  },
  id: {
    "title_site_info": "INFO SITUS",
    "cat_Aesthetic": "Estetik", "cat_Animal": "Hewan", "cat_Arrow": "Panah", "cat_Award": "Penghargaan",
    "cat_Border": "Bingkai", "cat_Bracket": "Kurung", "cat_Bubble": "Gelembung", "cat_Card": "Kartu",
    "cat_Checkmark": "Centang", "cat_Chess": "Catur", "cat_Chinese": "Cina", "cat_Circle": "Lingkaran",
    "cat_Comparison": "Perbandingan", "cat_Copyright": "Hak Cipta", "cat_Corner": "Sudut",
    "cat_Cross": "Salib", "cat_Crown": "Mahkota", "cat_Crypto": "Kripto", "cat_Currency": "Mata Uang",
    "cat_Cursive": "Kursif", "cat_Diamond": "Berlian", "cat_Dice": "Dadu", "cat_Divider": "Pembagi",
    "cat_Dot": "Titik", "cat_Down Arrow": "Panah Bawah", "cat_Emoji Faces": "Wajah Emoji",
    "cat_Flower": "Bunga", "cat_Fraction": "Pecahan", "cat_Gender": "Gender", "cat_German": "Jerman",
    "cat_Greek": "Yunani", "cat_Hand": "Tangan", "cat_Heart": "Hati", "cat_House": "Rumah",
    "cat_Infinity": "Tak Terbatas", "cat_Japanese": "Jepang", "cat_Korean": "Korea", "cat_Line": "Garis",
    "cat_Loading": "Memuat", "cat_Lock": "Kunci", "cat_Math": "Matematika", "cat_Medal": "Medali",
    "cat_Medical": "Medis", "cat_Moon": "Bulan", "cat_Music": "Musik", "cat_Numbers": "Angka",
    "cat_Office": "Kantor", "cat_Old English": "Inggris Kuno", "cat_Punctuation": "Tanda Baca",
    "cat_Quotation": "Kutipan", "cat_Rectangle": "Persegi Panjang", "cat_Religion": "Agama",
    "cat_Roman Numerals": "Angka Romawi", "cat_Sparkle": "Kilau", "cat_Square": "Kotak",
    "cat_Star": "Bintang", "cat_Sun": "Matahari", "cat_Transport": "Transportasi", "cat_Triangle": "Segitiga",
    "cat_Unit": "Satuan", "cat_Up Arrow": "Panah Atas", "cat_Upside Down": "Terbalik",
    "cat_Warning": "Peringatan", "cat_Wave": "Gelombang", "cat_Weapon": "Senjata", "cat_Weather": "Cuaca",
    "cat_Writing": "Menulis", "cat_Zodiac": "Zodiak"
  },
  it: {
    "title_site_info": "INFO SITO",
    "cat_Aesthetic": "Estetico", "cat_Animal": "Animali", "cat_Arrow": "Frecce", "cat_Award": "Premi",
    "cat_Border": "Bordi", "cat_Bracket": "Parentesi", "cat_Bubble": "Bolle", "cat_Card": "Carte",
    "cat_Checkmark": "Spunte", "cat_Chess": "Scacchi", "cat_Chinese": "Cinese", "cat_Circle": "Cerchio",
    "cat_Comparison": "Confronto", "cat_Copyright": "Copyright", "cat_Corner": "Angoli",
    "cat_Cross": "Croce", "cat_Crown": "Corona", "cat_Crypto": "Cripto", "cat_Currency": "Valuta",
    "cat_Cursive": "Corsivo", "cat_Diamond": "Diamante", "cat_Dice": "Dadi", "cat_Divider": "Separatori",
    "cat_Dot": "Punti", "cat_Down Arrow": "Freccia giù", "cat_Emoji Faces": "Faccine Emoji",
    "cat_Flower": "Fiori", "cat_Fraction": "Frazioni", "cat_Gender": "Genere", "cat_German": "Tedesco",
    "cat_Greek": "Greco", "cat_Hand": "Mano", "cat_Heart": "Cuore", "cat_House": "Casa",
    "cat_Infinity": "Infinito", "cat_Japanese": "Giapponese", "cat_Korean": "Coreano", "cat_Line": "Linea",
    "cat_Loading": "Caricamento", "cat_Lock": "Lucchetto", "cat_Math": "Matematica", "cat_Medal": "Medaglia",
    "cat_Medical": "Medico", "cat_Moon": "Luna", "cat_Music": "Musica", "cat_Numbers": "Numeri",
    "cat_Office": "Ufficio", "cat_Old English": "Inglese Antico", "cat_Punctuation": "Punteggiatura",
    "cat_Quotation": "Virgolette", "cat_Rectangle": "Rettangolo", "cat_Religion": "Religione",
    "cat_Roman Numerals": "Numeri Romani", "cat_Sparkle": "Scintilla", "cat_Square": "Quadrato",
    "cat_Star": "Stella", "cat_Sun": "Sole", "cat_Transport": "Trasporto", "cat_Triangle": "Triangolo",
    "cat_Unit": "Unità", "cat_Up Arrow": "Freccia su", "cat_Upside Down": "Capovolto",
    "cat_Warning": "Avvertimento", "cat_Wave": "Onda", "cat_Weapon": "Armi", "cat_Weather": "Meteo",
    "cat_Writing": "Scrittura", "cat_Zodiac": "Zodiaco"
  },
  ja: {
    "title_site_info": "サイト情報",
    "cat_Aesthetic": "特殊・絵文字", "cat_Animal": "動物", "cat_Arrow": "矢印", "cat_Award": "賞",
    "cat_Border": "罫線", "cat_Bracket": "括弧", "cat_Bubble": "囲み文字", "cat_Card": "カード",
    "cat_Checkmark": "チェックマーク", "cat_Chess": "チェス", "cat_Chinese": "中国語", "cat_Circle": "丸",
    "cat_Comparison": "比較", "cat_Copyright": "著作権", "cat_Corner": "角",
    "cat_Cross": "十字架", "cat_Crown": "王冠", "cat_Crypto": "暗号通貨", "cat_Currency": "通貨",
    "cat_Cursive": "筆記体", "cat_Diamond": "ダイヤモンド", "cat_Dice": "サイコロ", "cat_Divider": "区切り線",
    "cat_Dot": "点", "cat_Down Arrow": "下矢印", "cat_Emoji Faces": "顔文字",
    "cat_Flower": "花", "cat_Fraction": "分数", "cat_Gender": "性別", "cat_German": "ドイツ語",
    "cat_Greek": "ギリシャ語", "cat_Hand": "手", "cat_Heart": "ハート", "cat_House": "家",
    "cat_Infinity": "無限", "cat_Japanese": "日本語", "cat_Korean": "韓国語", "cat_Line": "線",
    "cat_Loading": "読込中", "cat_Lock": "鍵", "cat_Math": "数学", "cat_Medal": "メダル",
    "cat_Medical": "医療", "cat_Moon": "月", "cat_Music": "音楽", "cat_Numbers": "数字",
    "cat_Office": "オフィス", "cat_Old English": "古英語", "cat_Punctuation": "句読点",
    "cat_Quotation": "引用符", "cat_Rectangle": "長方形", "cat_Religion": "宗教",
    "cat_Roman Numerals": "ローマ数字", "cat_Sparkle": "キラキラ", "cat_Square": "四角",
    "cat_Star": "星", "cat_Sun": "太陽", "cat_Transport": "乗り物", "cat_Triangle": "三角",
    "cat_Unit": "単位", "cat_Up Arrow": "上矢印", "cat_Upside Down": "逆さ",
    "cat_Warning": "警告", "cat_Wave": "波", "cat_Weapon": "武器", "cat_Weather": "天気",
    "cat_Writing": "書く", "cat_Zodiac": "星座"
  },
  ko: {
    "title_site_info": "사이트 정보",
    "cat_Aesthetic": "감성", "cat_Animal": "동물", "cat_Arrow": "화살표", "cat_Award": "상",
    "cat_Border": "테두리", "cat_Bracket": "괄호", "cat_Bubble": "말풍선", "cat_Card": "카드",
    "cat_Checkmark": "체크표시", "cat_Chess": "체스", "cat_Chinese": "중국어", "cat_Circle": "원",
    "cat_Comparison": "비교", "cat_Copyright": "저작권", "cat_Corner": "코너",
    "cat_Cross": "십자가", "cat_Crown": "왕관", "cat_Crypto": "암호화폐", "cat_Currency": "통화",
    "cat_Cursive": "필기체", "cat_Diamond": "다이아몬드", "cat_Dice": "주사위", "cat_Divider": "구분선",
    "cat_Dot": "점", "cat_Down Arrow": "아래 화살표", "cat_Emoji Faces": "이모지 얼굴",
    "cat_Flower": "꽃", "cat_Fraction": "분수", "cat_Gender": "성별", "cat_German": "독일어",
    "cat_Greek": "그리스어", "cat_Hand": "손", "cat_Heart": "하트", "cat_House": "집",
    "cat_Infinity": "무한대", "cat_Japanese": "일본어", "cat_Korean": "한국어", "cat_Line": "선",
    "cat_Loading": "로딩", "cat_Lock": "자물쇠", "cat_Math": "수학", "cat_Medal": "메달",
    "cat_Medical": "의료", "cat_Moon": "달", "cat_Music": "음악", "cat_Numbers": "숫자",
    "cat_Office": "사무실", "cat_Old English": "고대영어", "cat_Punctuation": "구두점",
    "cat_Quotation": "따옴표", "cat_Rectangle": "직사각형", "cat_Religion": "종교",
    "cat_Roman Numerals": "로마 숫자", "cat_Sparkle": "반짝이", "cat_Square": "사각형",
    "cat_Star": "별", "cat_Sun": "태양", "cat_Transport": "교통", "cat_Triangle": "삼각형",
    "cat_Unit": "단위", "cat_Up Arrow": "위 화살표", "cat_Upside Down": "뒤집기",
    "cat_Warning": "경고", "cat_Wave": "물결", "cat_Weapon": "무기", "cat_Weather": "날씨",
    "cat_Writing": "쓰기", "cat_Zodiac": "별자리"
  },
  ms: {
    "title_site_info": "INFO LAMAN",
    "cat_Aesthetic": "Estetik", "cat_Animal": "Haiwan", "cat_Arrow": "Anak Panah", "cat_Award": "Anugerah",
    "cat_Border": "Sempadan", "cat_Bracket": "Kurungan", "cat_Bubble": "Buih", "cat_Card": "Kad",
    "cat_Checkmark": "Tanda", "cat_Chess": "Catur", "cat_Chinese": "Cina", "cat_Circle": "Bulatan",
    "cat_Comparison": "Perbandingan", "cat_Copyright": "Hak Cipta", "cat_Corner": "Sudut",
    "cat_Cross": "Salib", "cat_Crown": "Mahkota", "cat_Crypto": "Kripto", "cat_Currency": "Mata Wang",
    "cat_Cursive": "Kursif", "cat_Diamond": "Berlian", "cat_Dice": "Dadu", "cat_Divider": "Pembahagi",
    "cat_Dot": "Titik", "cat_Down Arrow": "Panah Bawah", "cat_Emoji Faces": "Muka Emoji",
    "cat_Flower": "Bunga", "cat_Fraction": "Pecahan", "cat_Gender": "Jantina", "cat_German": "Jerman",
    "cat_Greek": "Yunani", "cat_Hand": "Tangan", "cat_Heart": "Hati", "cat_House": "Rumah",
    "cat_Infinity": "Infiniti", "cat_Japanese": "Jepun", "cat_Korean": "Korea", "cat_Line": "Garisan",
    "cat_Loading": "Memuatkan", "cat_Lock": "Kunci", "cat_Math": "Matematik", "cat_Medal": "Pingat",
    "cat_Medical": "Perubatan", "cat_Moon": "Bulan", "cat_Music": "Muzik", "cat_Numbers": "Nombor",
    "cat_Office": "Pejabat", "cat_Old English": "Inggeris Lama", "cat_Punctuation": "Tanda Baca",
    "cat_Quotation": "Petikan", "cat_Rectangle": "Segi Empat", "cat_Religion": "Agama",
    "cat_Roman Numerals": "Angka Rom", "cat_Sparkle": "Kilauan", "cat_Square": "Petak",
    "cat_Star": "Bintang", "cat_Sun": "Matahari", "cat_Transport": "Pengangkutan", "cat_Triangle": "Segi Tiga",
    "cat_Unit": "Unit", "cat_Up Arrow": "Panah Atas", "cat_Upside Down": "Terbalik",
    "cat_Warning": "Amaran", "cat_Wave": "Ombak", "cat_Weapon": "Senjata", "cat_Weather": "Cuaca",
    "cat_Writing": "Menulis", "cat_Zodiac": "Zodiak"
  },
  pl: {
    "title_site_info": "INFO O STRONIE",
    "cat_Aesthetic": "Estetyczne", "cat_Animal": "Zwierzęta", "cat_Arrow": "Strzałki", "cat_Award": "Nagrody",
    "cat_Border": "Ramki", "cat_Bracket": "Nawiasy", "cat_Bubble": "Bąbelki", "cat_Card": "Karty",
    "cat_Checkmark": "Ptaszki", "cat_Chess": "Szachy", "cat_Chinese": "Chiński", "cat_Circle": "Koło",
    "cat_Comparison": "Porównanie", "cat_Copyright": "Prawa autorskie", "cat_Corner": "Narożniki",
    "cat_Cross": "Krzyż", "cat_Crown": "Korona", "cat_Crypto": "Krypto", "cat_Currency": "Waluta",
    "cat_Cursive": "Kursywa", "cat_Diamond": "Diament", "cat_Dice": "Kostki", "cat_Divider": "Separatory",
    "cat_Dot": "Kropki", "cat_Down Arrow": "Strzałka w dół", "cat_Emoji Faces": "Twarze Emoji",
    "cat_Flower": "Kwiaty", "cat_Fraction": "Ułamki", "cat_Gender": "Płeć", "cat_German": "Niemiecki",
    "cat_Greek": "Grecki", "cat_Hand": "Ręka", "cat_Heart": "Serce", "cat_House": "Dom",
    "cat_Infinity": "Nieskończoność", "cat_Japanese": "Japoński", "cat_Korean": "Koreański", "cat_Line": "Linia",
    "cat_Loading": "Ładowanie", "cat_Lock": "Kłódka", "cat_Math": "Matematyka", "cat_Medal": "Medal",
    "cat_Medical": "Medyczne", "cat_Moon": "Księżyc", "cat_Music": "Muzyka", "cat_Numbers": "Liczby",
    "cat_Office": "Biuro", "cat_Old English": "Stary Angielski", "cat_Punctuation": "Interpunkcja",
    "cat_Quotation": "Cudzysłowy", "cat_Rectangle": "Prostokąt", "cat_Religion": "Religia",
    "cat_Roman Numerals": "Cyfry Rzymskie", "cat_Sparkle": "Iskra", "cat_Square": "Kwadrat",
    "cat_Star": "Gwiazda", "cat_Sun": "Słońce", "cat_Transport": "Transport", "cat_Triangle": "Trójkąt",
    "cat_Unit": "Jednostki", "cat_Up Arrow": "Strzałka w górę", "cat_Upside Down": "Do góry nogami",
    "cat_Warning": "Ostrzeżenie", "cat_Wave": "Fala", "cat_Weapon": "Broń", "cat_Weather": "Pogoda",
    "cat_Writing": "Pisanie", "cat_Zodiac": "Zodiaki"
  },
  pt: {
    "title_site_info": "INFO DO SITE",
    "cat_Aesthetic": "Estético", "cat_Animal": "Animais", "cat_Arrow": "Setas", "cat_Award": "Prêmios",
    "cat_Border": "Bordas", "cat_Bracket": "Colchetes", "cat_Bubble": "Bolhas", "cat_Card": "Cartas",
    "cat_Checkmark": "Marcas", "cat_Chess": "Xadrez", "cat_Chinese": "Chinês", "cat_Circle": "Círculo",
    "cat_Comparison": "Comparação", "cat_Copyright": "Direitos", "cat_Corner": "Cantos",
    "cat_Cross": "Cruz", "cat_Crown": "Coroa", "cat_Crypto": "Cripto", "cat_Currency": "Moeda",
    "cat_Cursive": "Cursivo", "cat_Diamond": "Diamante", "cat_Dice": "Dados", "cat_Divider": "Divisores",
    "cat_Dot": "Pontos", "cat_Down Arrow": "Seta para baixo", "cat_Emoji Faces": "Caras Emoji",
    "cat_Flower": "Flores", "cat_Fraction": "Frações", "cat_Gender": "Gênero", "cat_German": "Alemão",
    "cat_Greek": "Grego", "cat_Hand": "Mão", "cat_Heart": "Coração", "cat_House": "Casa",
    "cat_Infinity": "Infinito", "cat_Japanese": "Japonês", "cat_Korean": "Coreano", "cat_Line": "Linha",
    "cat_Loading": "Carregando", "cat_Lock": "Cadeado", "cat_Math": "Matemática", "cat_Medal": "Medalha",
    "cat_Medical": "Médico", "cat_Moon": "Lua", "cat_Music": "Música", "cat_Numbers": "Números",
    "cat_Office": "Escritório", "cat_Old English": "Inglês Antigo", "cat_Punctuation": "Pontuação",
    "cat_Quotation": "Aspas", "cat_Rectangle": "Retângulo", "cat_Religion": "Religião",
    "cat_Roman Numerals": "Números Romanos", "cat_Sparkle": "Brilho", "cat_Square": "Quadrado",
    "cat_Star": "Estrela", "cat_Sun": "Sol", "cat_Transport": "Transporte", "cat_Triangle": "Triângulo",
    "cat_Unit": "Unidades", "cat_Up Arrow": "Seta para cima", "cat_Upside Down": "De cabeça para baixo",
    "cat_Warning": "Aviso", "cat_Wave": "Onda", "cat_Weapon": "Armas", "cat_Weather": "Clima",
    "cat_Writing": "Escrita", "cat_Zodiac": "Zodíaco"
  },
  ru: {
    "title_site_info": "ИНФОРМАЦИЯ О САЙТЕ",
    "cat_Aesthetic": "Эстетика", "cat_Animal": "Животные", "cat_Arrow": "Стрелки", "cat_Award": "Награды",
    "cat_Border": "Рамки", "cat_Bracket": "Скобки", "cat_Bubble": "Пузырьки", "cat_Card": "Карты",
    "cat_Checkmark": "Галочки", "cat_Chess": "Шахматы", "cat_Chinese": "Китайские", "cat_Circle": "Круг",
    "cat_Comparison": "Сравнение", "cat_Copyright": "Авторские права", "cat_Corner": "Углы",
    "cat_Cross": "Крест", "cat_Crown": "Корона", "cat_Crypto": "Крипто", "cat_Currency": "Валюта",
    "cat_Cursive": "Курсив", "cat_Diamond": "Бриллиант", "cat_Dice": "Кости", "cat_Divider": "Разделители",
    "cat_Dot": "Точки", "cat_Down Arrow": "Стрелка вниз", "cat_Emoji Faces": "Эмодзи Лица",
    "cat_Flower": "Цветы", "cat_Fraction": "Дроби", "cat_Gender": "Пол", "cat_German": "Немецкие",
    "cat_Greek": "Греческие", "cat_Hand": "Рука", "cat_Heart": "Сердце", "cat_House": "Дом",
    "cat_Infinity": "Бесконечность", "cat_Japanese": "Японские", "cat_Korean": "Корейские", "cat_Line": "Линия",
    "cat_Loading": "Загрузка", "cat_Lock": "Замок", "cat_Math": "Математика", "cat_Medal": "Медаль",
    "cat_Medical": "Медицина", "cat_Moon": "Луна", "cat_Music": "Музыка", "cat_Numbers": "Числа",
    "cat_Office": "Офис", "cat_Old English": "Старый Английский", "cat_Punctuation": "Пунктуация",
    "cat_Quotation": "Кавычки", "cat_Rectangle": "Прямоугольник", "cat_Religion": "Религия",
    "cat_Roman Numerals": "Римские Цифры", "cat_Sparkle": "Блеск", "cat_Square": "Квадрат",
    "cat_Star": "Звезда", "cat_Sun": "Солнце", "cat_Transport": "Транспорт", "cat_Triangle": "Треугольник",
    "cat_Unit": "Единицы", "cat_Up Arrow": "Стрелка вверх", "cat_Upside Down": "Перевёрнутый",
    "cat_Warning": "Предупреждение", "cat_Wave": "Волна", "cat_Weapon": "Оружие", "cat_Weather": "Погода",
    "cat_Writing": "Письмо", "cat_Zodiac": "Зодиак"
  },
  sv: {
    "title_site_info": "SAJTINFO",
    "cat_Aesthetic": "Estetisk", "cat_Animal": "Djur", "cat_Arrow": "Pilar", "cat_Award": "Utmärkelser",
    "cat_Border": "Ramar", "cat_Bracket": "Parenteser", "cat_Bubble": "Bubblor", "cat_Card": "Kort",
    "cat_Checkmark": "Bockar", "cat_Chess": "Schack", "cat_Chinese": "Kinesiska", "cat_Circle": "Cirkel",
    "cat_Comparison": "Jämförelse", "cat_Copyright": "Upphovsrätt", "cat_Corner": "Hörn",
    "cat_Cross": "Kors", "cat_Crown": "Krona", "cat_Crypto": "Krypto", "cat_Currency": "Valuta",
    "cat_Cursive": "Kursiv", "cat_Diamond": "Diamant", "cat_Dice": "Tärning", "cat_Divider": "Avdelare",
    "cat_Dot": "Punkter", "cat_Down Arrow": "Pil ned", "cat_Emoji Faces": "Emoji Ansikten",
    "cat_Flower": "Blommor", "cat_Fraction": "Bråktal", "cat_Gender": "Kön", "cat_German": "Tyska",
    "cat_Greek": "Grekiska", "cat_Hand": "Hand", "cat_Heart": "Hjärta", "cat_House": "Hus",
    "cat_Infinity": "Oändlighet", "cat_Japanese": "Japanska", "cat_Korean": "Koreanska", "cat_Line": "Linje",
    "cat_Loading": "Laddar", "cat_Lock": "Lås", "cat_Math": "Matte", "cat_Medal": "Medalj",
    "cat_Medical": "Medicinsk", "cat_Moon": "Måne", "cat_Music": "Musik", "cat_Numbers": "Nummer",
    "cat_Office": "Kontor", "cat_Old English": "Gammal engelska", "cat_Punctuation": "Skiljetecken",
    "cat_Quotation": "Citattecken", "cat_Rectangle": "Rektangel", "cat_Religion": "Religion",
    "cat_Roman Numerals": "Romerska Siffror", "cat_Sparkle": "Glitter", "cat_Square": "Fyrkant",
    "cat_Star": "Stjärna", "cat_Sun": "Sol", "cat_Transport": "Transport", "cat_Triangle": "Triangel",
    "cat_Unit": "Enheter", "cat_Up Arrow": "Pil upp", "cat_Upside Down": "Upp och Ner",
    "cat_Warning": "Varning", "cat_Wave": "Våg", "cat_Weapon": "Vapen", "cat_Weather": "Väder",
    "cat_Writing": "Skrivande", "cat_Zodiac": "Zodiaken"
  },
  tr: {
    "title_site_info": "SİTE BİLGİSİ",
    "cat_Aesthetic": "Estetik", "cat_Animal": "Hayvan", "cat_Arrow": "Ok", "cat_Award": "Ödül",
    "cat_Border": "Kenarlık", "cat_Bracket": "Parantez", "cat_Bubble": "Balon", "cat_Card": "Kart",
    "cat_Checkmark": "Onay", "cat_Chess": "Satranç", "cat_Chinese": "Çince", "cat_Circle": "Daire",
    "cat_Comparison": "Karşılaştırma", "cat_Copyright": "Telif Hakkı", "cat_Corner": "Köşe",
    "cat_Cross": "Haç", "cat_Crown": "Taç", "cat_Crypto": "Kripto", "cat_Currency": "Para Birimi",
    "cat_Cursive": "El Yazısı", "cat_Diamond": "Elmas", "cat_Dice": "Zar", "cat_Divider": "Ayırıcı",
    "cat_Dot": "Nokta", "cat_Down Arrow": "Aşağı Ok", "cat_Emoji Faces": "Emoji Yüzler",
    "cat_Flower": "Çiçek", "cat_Fraction": "Kesir", "cat_Gender": "Cinsiyet", "cat_German": "Almanca",
    "cat_Greek": "Yunanca", "cat_Hand": "El", "cat_Heart": "Kalp", "cat_House": "Ev",
    "cat_Infinity": "Sonsuzluk", "cat_Japanese": "Japonca", "cat_Korean": "Korece", "cat_Line": "Çizgi",
    "cat_Loading": "Yükleniyor", "cat_Lock": "Kilit", "cat_Math": "Matematik", "cat_Medal": "Madalya",
    "cat_Medical": "Tıbbi", "cat_Moon": "Ay", "cat_Music": "Müzik", "cat_Numbers": "Sayılar",
    "cat_Office": "Ofis", "cat_Old English": "Eski İngilizce", "cat_Punctuation": "Noktalama",
    "cat_Quotation": "Tırnak İşareti", "cat_Rectangle": "Dikdörtgen", "cat_Religion": "Din",
    "cat_Roman Numerals": "Roma Rakamları", "cat_Sparkle": "Parıltı", "cat_Square": "Kare",
    "cat_Star": "Yıldız", "cat_Sun": "Güneş", "cat_Transport": "Ulaşım", "cat_Triangle": "Üçgen",
    "cat_Unit": "Birim", "cat_Up Arrow": "Yukarı Ok", "cat_Upside Down": "Baş aşağı",
    "cat_Warning": "Uyarı", "cat_Wave": "Dalga", "cat_Weapon": "Silah", "cat_Weather": "Hava Durumu",
    "cat_Writing": "Yazı", "cat_Zodiac": "Burç"
  }
};

for (const [lang, translations] of Object.entries(langData)) {
  const filePath = path.join(translationsDir, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    try {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      const merged = { ...data, ...translations };
      fs.writeFileSync(filePath, JSON.stringify(merged, null, 2), 'utf8');
      console.log(`Updated ${lang}.json with category translations`);
    } catch (e) {
      console.error(`Error updating ${lang}.json:`, e);
    }
  }
}
