const fs = require('fs');
const path = require('path');

const translationsDir = path.join(__dirname, '..', 'translations');

const langData = {
  ar: {
    "title_navigation": "الملاحة",
    "title_symbols_for": "رموز لـ",
    "title_text_tools": "أدوات النص",
    "title_trending_now": "شائع الآن",
    "title_all_categories": "جميع الفئات",
    "title_generators": "المولدات",
    "title_top_categories": "أهم الفئات",
    "title_discover": "اكتشف",
    "title_company": "الشركة",
    "link_instagram_symbols": "رموز إنستغرام",
    "link_discord_symbols": "رموز ديسكورد",
    "link_tiktok_symbols": "رموز تيك توك",
    "link_roblox_symbols": "رموز روبلوكس",
    "link_bio_generator": "مولد السيرة الذاتية",
    "link_username_generator": "مولد اسم المستخدم",
    "link_character_counter": "عداد الحروف",
    "link_strikethrough_text": "نص مشطوب",
    "link_emoticons": "الرموز التعبيرية والكاوموجي",
    "link_invisible_character": "حرف غير مرئي",
    "link_blank_space": "مسافة فارغة",
    "link_bullet_points": "نقاط تعدادية",
    "link_free_fire_names": "أسماء فري فاير",
    "link_zalgo_text": "نص زالغو",
    "link_text_repeater": "مكرر النص",
    "link_small_text": "نص صغير",
    "link_bold_text": "نص عريض",
    "link_morse_code": "شفرة مورس",
    "link_cursive_text": "نص متصل",
    "link_upside_down_text": "نص مقلوب",
    "link_vaporwave_text": "نص فيبورغريف",
    "link_bubble_text": "نص فقاعي",
    "link_gothic_text": "نص غوطي",
    "link_heart_symbols": "رموز القلب",
    "link_star_symbols": "رموز النجمة",
    "link_aesthetic_symbols": "رموز جمالية",
    "link_arrow_symbols": "رموز الأسهم",
    "link_flower_symbols": "رموز الزهور",
    "link_check_marks": "علامات الاختيار",
    "link_emoji_faces": "وجوه تعبيرية",
    "link_math_symbols": "رموز رياضية",
    "link_japanese_symbols": "رموز يابانية",
    "link_korean_symbols": "رموز كورية",
    "link_music_symbols": "رموز موسيقية",
    "link_cross_symbols": "رموز الصليب",
    "link_about_us": "من نحن",
    "link_contact_us": "اتصل بنا",
    "link_authors_team": "المؤلفون والفريق",
    "link_editorial_guidelines": "إرشادات التحرير",
    "link_sitemap": "خريطة الموقع",
    "link_privacy_policy": "سياسة الخصوصية",
    "link_terms_of_service": "شروط الخدمة"
  },
  bg: {
    "title_navigation": "НАВИГАЦИЯ",
    "title_symbols_for": "СИМВОЛИ ЗА",
    "title_text_tools": "ИНСТРУМЕНТИ ЗА ТЕКСТ",
    "title_trending_now": "ПОПУЛЯРНИ СЕГА",
    "title_all_categories": "ВСИЧКИ КАТЕГОРИИ",
    "title_generators": "Генератори",
    "title_top_categories": "Топ Категории",
    "title_discover": "Открийте",
    "title_company": "Компания",
    "link_instagram_symbols": "Символи за Instagram",
    "link_discord_symbols": "Символи за Discord",
    "link_tiktok_symbols": "Символи за TikTok",
    "link_roblox_symbols": "Символи за Roblox",
    "link_bio_generator": "Генератор на Био",
    "link_username_generator": "Генератор на Потребителски Имена",
    "link_character_counter": "Брояч на Символи",
    "link_strikethrough_text": "Зачеркнат Текст",
    "link_emoticons": "Емотикони и Каомоджи",
    "link_invisible_character": "Невидим Символ",
    "link_blank_space": "Празно Пространство",
    "link_bullet_points": "Точки за Списък",
    "link_free_fire_names": "Имена за Free Fire",
    "link_zalgo_text": "Залго Текст",
    "link_text_repeater": "Повторител на Текст",
    "link_small_text": "Малък Текст",
    "link_bold_text": "Удебелен Текст",
    "link_morse_code": "Морзова Азбука",
    "link_cursive_text": "Ръкописен Текст",
    "link_upside_down_text": "Обърнат Текст",
    "link_vaporwave_text": "Вейпъруейв Текст",
    "link_bubble_text": "Текст в Мехурчета",
    "link_gothic_text": "Готически Текст",
    "link_heart_symbols": "Символи Сърце",
    "link_star_symbols": "Символи Звезда",
    "link_aesthetic_symbols": "Естетични Символи",
    "link_arrow_symbols": "Символи Стрелки",
    "link_flower_symbols": "Символи Цветя",
    "link_check_marks": "Отметки",
    "link_emoji_faces": "Емоджи Лица",
    "link_math_symbols": "Математически Символи",
    "link_japanese_symbols": "Японски Символи",
    "link_korean_symbols": "Корейски Символи",
    "link_music_symbols": "Музикални Символи",
    "link_cross_symbols": "Символи Кръст",
    "link_about_us": "За Нас",
    "link_contact_us": "Контакти",
    "link_authors_team": "Автори и Екип",
    "link_editorial_guidelines": "Редакционни Насоки",
    "link_sitemap": "Карта на Сайта",
    "link_privacy_policy": "Политика за Поверителност",
    "link_terms_of_service": "Условия за Ползване"
  },
  bn: {
    "title_navigation": "নেভিগেশন",
    "title_symbols_for": "প্রতীকসমূহ",
    "title_text_tools": "টেক্সট টুলস",
    "title_trending_now": "এখন ট্রেন্ডিং",
    "title_all_categories": "সব ক্যাটাগরি",
    "title_generators": "জেনারেটর",
    "title_top_categories": "সেরা ক্যাটাগরি",
    "title_discover": "আবিষ্কার করুন",
    "title_company": "কোম্পানি",
    "link_instagram_symbols": "ইনস্টাগ্রাম প্রতীক",
    "link_discord_symbols": "ডিসকর্ড প্রতীক",
    "link_tiktok_symbols": "টিকটক প্রতীক",
    "link_roblox_symbols": "রবলক্স প্রতীক",
    "link_bio_generator": "বায়ো জেনারেটর",
    "link_username_generator": "ইউজারনেম জেনারেটর",
    "link_character_counter": "অক্ষর কাউন্টার",
    "link_strikethrough_text": "স্ট্রাইকথ্রু টেক্সট",
    "link_emoticons": "ইমোটিকন ও কাওমোজি",
    "link_invisible_character": "অদৃশ্য অক্ষর",
    "link_blank_space": "খালি জায়গা",
    "link_bullet_points": "বুলেট পয়েন্ট",
    "link_free_fire_names": "ফ্রি ফায়ার নাম",
    "link_zalgo_text": "জালগো টেক্সট",
    "link_text_repeater": "টেক্সট রিপিটার",
    "link_small_text": "ছোট টেক্সট",
    "link_bold_text": "বোল্ড টেক্সট",
    "link_morse_code": "মোর্স কোড",
    "link_cursive_text": "কার্সিভ টেক্সট",
    "link_upside_down_text": "উল্টো টেক্সট",
    "link_vaporwave_text": "ভেপারওয়েভ টেক্সট",
    "link_bubble_text": "বাবল টেক্সট",
    "link_gothic_text": "গথিক টেক্সট",
    "link_heart_symbols": "হার্ট প্রতীক",
    "link_star_symbols": "স্টার প্রতীক",
    "link_aesthetic_symbols": "নান্দনিক প্রতীক",
    "link_arrow_symbols": "তীর প্রতীক",
    "link_flower_symbols": "ফুল প্রতীক",
    "link_check_marks": "টিক চিহ্ন",
    "link_emoji_faces": "ইমোজি ফেস",
    "link_math_symbols": "গণিত প্রতীক",
    "link_japanese_symbols": "জাপানি প্রতীক",
    "link_korean_symbols": "কোরিয়ান প্রতীক",
    "link_music_symbols": "সঙ্গীত প্রতীক",
    "link_cross_symbols": "ক্রস প্রতীক",
    "link_about_us": "আমাদের সম্পর্কে",
    "link_contact_us": "যোগাযোগ",
    "link_authors_team": "লেখক ও দল",
    "link_editorial_guidelines": "সম্পাদকীয় নির্দেশিকা",
    "link_sitemap": "সাইটম্যাপ",
    "link_privacy_policy": "গোপনীয়তা নীতি",
    "link_terms_of_service": "পরিষেবার শর্তাবলী"
  },
  de: {
    "title_navigation": "NAVIGATION",
    "title_symbols_for": "SYMBOLE FÜR",
    "title_text_tools": "TEXTWERKZEUGE",
    "title_trending_now": "JETZT TRENDING",
    "title_all_categories": "ALLE KATEGORIEN",
    "title_generators": "Generatoren",
    "title_top_categories": "Top-Kategorien",
    "title_discover": "Entdecken",
    "title_company": "Unternehmen",
    "link_instagram_symbols": "Instagram Symbole",
    "link_discord_symbols": "Discord Symbole",
    "link_tiktok_symbols": "TikTok Symbole",
    "link_roblox_symbols": "Roblox Symbole",
    "link_bio_generator": "Bio Generator",
    "link_username_generator": "Benutzername Generator",
    "link_character_counter": "Zeichenzähler",
    "link_strikethrough_text": "Durchgestrichener Text",
    "link_emoticons": "Emoticons & Kaomoji",
    "link_invisible_character": "Unsichtbares Zeichen",
    "link_blank_space": "Leerzeichen",
    "link_bullet_points": "Aufzählungspunkte",
    "link_free_fire_names": "Free Fire Namen",
    "link_zalgo_text": "Zalgo Text",
    "link_text_repeater": "Textwiederholer",
    "link_small_text": "Kleiner Text",
    "link_bold_text": "Fetter Text",
    "link_morse_code": "Morsecode",
    "link_cursive_text": "Kursiver Text",
    "link_upside_down_text": "Kopfstehender Text",
    "link_vaporwave_text": "Vaporwave Text",
    "link_bubble_text": "Blasentext",
    "link_gothic_text": "Gotischer Text",
    "link_heart_symbols": "Herzsymbole",
    "link_star_symbols": "Sternsymbole",
    "link_aesthetic_symbols": "Aesthetische Symbole",
    "link_arrow_symbols": "Pfeilsymbole",
    "link_flower_symbols": "Blumensymbole",
    "link_check_marks": "Häkchen",
    "link_emoji_faces": "Emoji-Gesichter",
    "link_math_symbols": "Mathesymbole",
    "link_japanese_symbols": "Japanische Symbole",
    "link_korean_symbols": "Koreanische Symbole",
    "link_music_symbols": "Musiksymbole",
    "link_cross_symbols": "Kreuzsymbole",
    "link_about_us": "Über uns",
    "link_contact_us": "Kontakt",
    "link_authors_team": "Autoren & Team",
    "link_editorial_guidelines": "Redaktionelle Richtlinien",
    "link_sitemap": "Sitemap",
    "link_privacy_policy": "Datenschutz",
    "link_terms_of_service": "Nutzungsbedingungen"
  },
  es: {
    "title_navigation": "NAVEGACIÓN",
    "title_symbols_for": "SÍMBOLOS PARA",
    "title_text_tools": "HERRAMIENTAS DE TEXTO",
    "title_trending_now": "TENDENCIA AHORA",
    "title_all_categories": "TODAS LAS CATEGORÍAS",
    "title_generators": "Generadores",
    "title_top_categories": "Categorías Principales",
    "title_discover": "Descubrir",
    "title_company": "Compañía",
    "link_instagram_symbols": "Símbolos para Instagram",
    "link_discord_symbols": "Símbolos para Discord",
    "link_tiktok_symbols": "Símbolos para TikTok",
    "link_roblox_symbols": "Símbolos para Roblox",
    "link_bio_generator": "Generador de Biografías",
    "link_username_generator": "Generador de Nombres de Usuario",
    "link_character_counter": "Contador de Caracteres",
    "link_strikethrough_text": "Texto Tachado",
    "link_emoticons": "Emoticonos y Kaomoji",
    "link_invisible_character": "Carácter Invisible",
    "link_blank_space": "Espacio en Blanco",
    "link_bullet_points": "Puntos de Viñeta",
    "link_free_fire_names": "Nombres para Free Fire",
    "link_zalgo_text": "Texto Zalgo",
    "link_text_repeater": "Repetidor de Texto",
    "link_small_text": "Texto Pequeño",
    "link_bold_text": "Texto en Negrita",
    "link_morse_code": "Código Morse",
    "link_cursive_text": "Texto Cursiva",
    "link_upside_down_text": "Texto al Revés",
    "link_vaporwave_text": "Texto Vaporwave",
    "link_bubble_text": "Texto de Burbuja",
    "link_gothic_text": "Texto Gótico",
    "link_heart_symbols": "Símbolos de Corazón",
    "link_star_symbols": "Símbolos de Estrella",
    "link_aesthetic_symbols": "Símbolos Aesthetic",
    "link_arrow_symbols": "Símbolos de Flecha",
    "link_flower_symbols": "Símbolos de Flor",
    "link_check_marks": "Marcas de Verificación",
    "link_emoji_faces": "Caras de Emoji",
    "link_math_symbols": "Símbolos Matemáticos",
    "link_japanese_symbols": "Símbolos Japoneses",
    "link_korean_symbols": "Símbolos Coreanos",
    "link_music_symbols": "Símbolos de Música",
    "link_cross_symbols": "Símbolos de Cruz",
    "link_about_us": "Sobre Nosotros",
    "link_contact_us": "Contáctenos",
    "link_authors_team": "Autores y Equipo",
    "link_editorial_guidelines": "Directrices Editoriales",
    "link_sitemap": "Mapa del Sitio",
    "link_privacy_policy": "Política de Privacidad",
    "link_terms_of_service": "Términos de Servicio"
  },
  fr: {
    "title_navigation": "NAVIGATION",
    "title_symbols_for": "SYMBOLES POUR",
    "title_text_tools": "OUTILS DE TEXTE",
    "title_trending_now": "TENDANCE ACTUELLE",
    "title_all_categories": "TOUTES LES CATÉGORIES",
    "title_generators": "Générateurs",
    "title_top_categories": "Meilleures Catégories",
    "title_discover": "Découvrir",
    "title_company": "Entreprise",
    "link_instagram_symbols": "Symboles Instagram",
    "link_discord_symbols": "Symboles Discord",
    "link_tiktok_symbols": "Symboles TikTok",
    "link_roblox_symbols": "Symboles Roblox",
    "link_bio_generator": "Générateur de Bio",
    "link_username_generator": "Générateur de Pseudo",
    "link_character_counter": "Compteur de Caractères",
    "link_strikethrough_text": "Texte Barré",
    "link_emoticons": "Émoticônes & Kaomoji",
    "link_invisible_character": "Caractère Invisible",
    "link_blank_space": "Espace Vide",
    "link_bullet_points": "Puces de Liste",
    "link_free_fire_names": "Noms Free Fire",
    "link_zalgo_text": "Texte Zalgo",
    "link_text_repeater": "Répéteur de Texte",
    "link_small_text": "Petit Texte",
    "link_bold_text": "Texte en Gras",
    "link_morse_code": "Code Morse",
    "link_cursive_text": "Texte Cursif",
    "link_upside_down_text": "Texte à l'Envers",
    "link_vaporwave_text": "Texte Vaporwave",
    "link_bubble_text": "Texte Bulle",
    "link_gothic_text": "Texte Gothique",
    "link_heart_symbols": "Symboles de Cœur",
    "link_star_symbols": "Symboles d'Étoile",
    "link_aesthetic_symbols": "Symboles Aesthetic",
    "link_arrow_symbols": "Symboles de Flèche",
    "link_flower_symbols": "Symboles de Fleur",
    "link_check_marks": "Coches",
    "link_emoji_faces": "Visages Emoji",
    "link_math_symbols": "Symboles Mathématiques",
    "link_japanese_symbols": "Symboles Japonais",
    "link_korean_symbols": "Symboles Coréens",
    "link_music_symbols": "Symboles de Musique",
    "link_cross_symbols": "Symboles de Croix",
    "link_about_us": "À Propos",
    "link_contact_us": "Contactez-nous",
    "link_authors_team": "Auteurs & Équipe",
    "link_editorial_guidelines": "Lignes Éditoriales",
    "link_sitemap": "Plan du Site",
    "link_privacy_policy": "Politique de Confidentialité",
    "link_terms_of_service": "Conditions d'Utilisation"
  },
  hi: {
    "title_navigation": "नेविगेशन",
    "title_symbols_for": "प्रतीक इनके लिए",
    "title_text_tools": "टेक्स्ट टूल्स",
    "title_trending_now": "अभी ट्रेंडिंग",
    "title_all_categories": "सभी श्रेणियां",
    "title_generators": "जेनरेटर",
    "title_top_categories": "शीर्ष श्रेणियां",
    "title_discover": "खोजें",
    "title_company": "कंपनी",
    "link_instagram_symbols": "इंस्टाग्राम प्रतीक",
    "link_discord_symbols": "डिस्कॉर्ड प्रतीक",
    "link_tiktok_symbols": "टिकटॉक प्रतीक",
    "link_roblox_symbols": "रोब्लॉक्स प्रतीक",
    "link_bio_generator": "बायो जेनरेटर",
    "link_username_generator": "यूज़रनेम जेनरेटर",
    "link_character_counter": "कैरेक्टर काउंटर",
    "link_strikethrough_text": "कटा हुआ टेक्स्ट",
    "link_emoticons": "इमोटिकॉन्स और काओमोजी",
    "link_invisible_character": "अदृश्य कैरेक्टर",
    "link_blank_space": "खाली जगह",
    "link_bullet_points": "बुलेट पॉइंट्स",
    "link_free_fire_names": "फ्री फायर नाम",
    "link_zalgo_text": "ज़ाल्गो टेक्स्ट",
    "link_text_repeater": "टेक्स्ट रिपीटर",
    "link_small_text": "छोटा टेक्स्ट",
    "link_bold_text": "बोल्ड टेक्स्ट",
    "link_morse_code": "मर्स कोड",
    "link_cursive_text": "कर्सिव टेक्स्ट",
    "link_upside_down_text": "उल्टा टेक्स्ट",
    "link_vaporwave_text": "वेपरवेव टेक्स्ट",
    "link_bubble_text": "बबल टेक्स्ट",
    "link_gothic_text": "गॉथिक टेक्स्ट",
    "link_heart_symbols": "दिल के प्रतीक",
    "link_star_symbols": "तारे के प्रतीक",
    "link_aesthetic_symbols": "सौंदर्यपूर्ण प्रतीक",
    "link_arrow_symbols": "तीर के प्रतीक",
    "link_flower_symbols": "फूलों के प्रतीक",
    "link_check_marks": "टिक के निशान",
    "link_emoji_faces": "इमोजी चेहरे",
    "link_math_symbols": "गणित के प्रतीक",
    "link_japanese_symbols": "जापानी प्रतीक",
    "link_korean_symbols": "कोरियाई प्रतीक",
    "link_music_symbols": "संगीत के प्रतीक",
    "link_cross_symbols": "क्रॉस के प्रतीक",
    "link_about_us": "हमारे बारे में",
    "link_contact_us": "संपर्क करें",
    "link_authors_team": "लेखक और टीम",
    "link_editorial_guidelines": "संपादकीय दिशानिर्देश",
    "link_sitemap": "साइटमैप",
    "link_privacy_policy": "गोपनीयता नीति",
    "link_terms_of_service": "सेवा की शर्तें"
  },
  id: {
    "title_navigation": "NAVIGASI",
    "title_symbols_for": "SIMBOL UNTUK",
    "title_text_tools": "ALAT TEKS",
    "title_trending_now": "TREN SEKARANG",
    "title_all_categories": "SEMUA KATEGORI",
    "title_generators": "Generator",
    "title_top_categories": "Kategori Utama",
    "title_discover": "Jelajahi",
    "title_company": "Perusahaan",
    "link_instagram_symbols": "Simbol Instagram",
    "link_discord_symbols": "Simbol Discord",
    "link_tiktok_symbols": "Simbol TikTok",
    "link_roblox_symbols": "Simbol Roblox",
    "link_bio_generator": "Generator Bio",
    "link_username_generator": "Generator Nama Pengguna",
    "link_character_counter": "Penghitung Karakter",
    "link_strikethrough_text": "Teks Dicoret",
    "link_emoticons": "Emotikon & Kaomoji",
    "link_invisible_character": "Karakter Tak Terlihat",
    "link_blank_space": "Spasi Kosong",
    "link_bullet_points": "Poin Bulat",
    "link_free_fire_names": "Nama Free Fire",
    "link_zalgo_text": "Teks Zalgo",
    "link_text_repeater": "Pengulang Teks",
    "link_small_text": "Teks Kecil",
    "link_bold_text": "Teks Tebal",
    "link_morse_code": "Kode Morse",
    "link_cursive_text": "Teks Cursive",
    "link_upside_down_text": "Teks Terbalik",
    "link_vaporwave_text": "Teks Vaporwave",
    "link_bubble_text": "Teks Gelembung",
    "link_gothic_text": "Teks Gotik",
    "link_heart_symbols": "Simbol Hati",
    "link_star_symbols": "Simbol Bintang",
    "link_aesthetic_symbols": "Simbol Estetik",
    "link_arrow_symbols": "Simbol Panah",
    "link_flower_symbols": "Simbol Bunga",
    "link_check_marks": "Tanda Centang",
    "link_emoji_faces": "Wajah Emoji",
    "link_math_symbols": "Simbol Matematika",
    "link_japanese_symbols": "Simbol Jepang",
    "link_korean_symbols": "Simbol Korea",
    "link_music_symbols": "Simbol Musik",
    "link_cross_symbols": "Simbol Salib",
    "link_about_us": "Tentang Kami",
    "link_contact_us": "Hubungi Kami",
    "link_authors_team": "Penulis & Tim",
    "link_editorial_guidelines": "Panduan Editorial",
    "link_sitemap": "Peta Situs",
    "link_privacy_policy": "Kebijakan Privasi",
    "link_terms_of_service": "Ketentuan Layanan"
  },
  it: {
    "title_navigation": "NAVIGAZIONE",
    "title_symbols_for": "SIMBOLI PER",
    "title_text_tools": "STRUMENTI DI TESTO",
    "title_trending_now": "TENDENZA ORA",
    "title_all_categories": "TUTTE LE CATEGORIE",
    "title_generators": "Generatori",
    "title_top_categories": "Categorie Principali",
    "title_discover": "Scopri",
    "title_company": "Azienda",
    "link_instagram_symbols": "Simboli Instagram",
    "link_discord_symbols": "Simboli Discord",
    "link_tiktok_symbols": "Simboli TikTok",
    "link_roblox_symbols": "Simboli Roblox",
    "link_bio_generator": "Generatore di Bio",
    "link_username_generator": "Generatore di Nomi Utente",
    "link_character_counter": "Conteggio Caratteri",
    "link_strikethrough_text": "Testo Barrato",
    "link_emoticons": "Emoticon & Kaomoji",
    "link_invisible_character": "Carattere Invisibile",
    "link_blank_space": "Spazio Vuoto",
    "link_bullet_points": "Punti Elenco",
    "link_free_fire_names": "Nomi Free Fire",
    "link_zalgo_text": "Testo Zalgo",
    "link_text_repeater": "Ripetitore di Testo",
    "link_small_text": "Testo Piccolo",
    "link_bold_text": "Testo in Grassetto",
    "link_morse_code": "Codice Morse",
    "link_cursive_text": "Testo Corsivo",
    "link_upside_down_text": "Testo Sotto-Sopra",
    "link_vaporwave_text": "Testo Vaporwave",
    "link_bubble_text": "Testo a Bolle",
    "link_gothic_text": "Testo Gotico",
    "link_heart_symbols": "Simboli Cuore",
    "link_star_symbols": "Simboli Stella",
    "link_aesthetic_symbols": "Simboli Aesthetic",
    "link_arrow_symbols": "Simboli Freccia",
    "link_flower_symbols": "Simboli Fiore",
    "link_check_marks": "Segni di Spunta",
    "link_emoji_faces": "Faccine Emoji",
    "link_math_symbols": "Simboli Matematici",
    "link_japanese_symbols": "Simboli Giapponesi",
    "link_korean_symbols": "Simboli Coreani",
    "link_music_symbols": "Simboli Musica",
    "link_cross_symbols": "Simboli Croce",
    "link_about_us": "Chi Siamo",
    "link_contact_us": "Contattaci",
    "link_authors_team": "Autori & Team",
    "link_editorial_guidelines": "Linee Guida Editoriali",
    "link_sitemap": "Mappa del Sito",
    "link_privacy_policy": "Informativa sulla Privacy",
    "link_terms_of_service": "Termini di Servizio"
  },
  ja: {
    "title_navigation": "ナビゲーション",
    "title_symbols_for": "対象別記号",
    "title_text_tools": "テキストツール",
    "title_trending_now": "トレンド",
    "title_all_categories": "すべてのカテゴリ",
    "title_generators": "ジェネレーター",
    "title_top_categories": "人気カテゴリ",
    "title_discover": "見つける",
    "title_company": "企業情報",
    "link_instagram_symbols": "Instagram用の記号",
    "link_discord_symbols": "Discord用の記号",
    "link_tiktok_symbols": "TikTok用の記号",
    "link_roblox_symbols": "Roblox用の記号",
    "link_bio_generator": "自己紹介ジェネレーター",
    "link_username_generator": "ユーザー名ジェネレーター",
    "link_character_counter": "文字数カウント",
    "link_strikethrough_text": "打ち消し線テキスト",
    "link_emoticons": "絵文字と顔文字",
    "link_invisible_character": "見えない文字",
    "link_blank_space": "空白文字",
    "link_bullet_points": "箇条書き記号",
    "link_free_fire_names": "Free Fireの名前",
    "link_zalgo_text": "ザルゴ文字",
    "link_text_repeater": "テキストリピーター",
    "link_small_text": "小さい文字",
    "link_bold_text": "太字テキスト",
    "link_morse_code": "モールス信号",
    "link_cursive_text": "筆記体テキスト",
    "link_upside_down_text": "逆さ文字",
    "link_vaporwave_text": "ヴェイパーウェイヴ文字",
    "link_bubble_text": "囲み文字",
    "link_gothic_text": "ゴシック文字",
    "link_heart_symbols": "ハート記号",
    "link_star_symbols": "星記号",
    "link_aesthetic_symbols": "特殊記号・絵文字",
    "link_arrow_symbols": "矢印記号",
    "link_flower_symbols": "花記号",
    "link_check_marks": "チェックマーク",
    "link_emoji_faces": "顔文字・顔絵文字",
    "link_math_symbols": "数学記号",
    "link_japanese_symbols": "日本の記号",
    "link_korean_symbols": "韓国の記号",
    "link_music_symbols": "音符・音楽記号",
    "link_cross_symbols": "十字架記号",
    "link_about_us": "運営者情報",
    "link_contact_us": "お問い合わせ",
    "link_authors_team": "著者とチーム",
    "link_editorial_guidelines": "編集方針",
    "link_sitemap": "サイトマップ",
    "link_privacy_policy": "プライバシーポリシー",
    "link_terms_of_service": "利用規約"
  },
  ko: {
    "title_navigation": "네비게이션",
    "title_symbols_for": "특정 플랫폼 기호",
    "title_text_tools": "텍스트 도구",
    "title_trending_now": "현재 인기 기호",
    "title_all_categories": "모든 카테고리",
    "title_generators": "폰트 생성기",
    "title_top_categories": "인기 카테고리",
    "title_discover": "더 알아보기",
    "title_company": "회사 소개",
    "link_instagram_symbols": "인스타그램 특수문자",
    "link_discord_symbols": "디스코드 특수문자",
    "link_tiktok_symbols": "틱톡 특수문자",
    "link_roblox_symbols": "로블록스 특수문자",
    "link_bio_generator": "인스타 줄바꿈 공백 생성기",
    "link_username_generator": "닉네임 추천 생성기",
    "link_character_counter": "글자수 세기",
    "link_strikethrough_text": "취소선 텍스트",
    "link_emoticons": "귀여운 이모티콘 & 카오모지",
    "link_invisible_character": "공백 문자",
    "link_blank_space": "공백 복사",
    "link_bullet_points": "글머리 기호",
    "link_free_fire_names": "프리 파이어 닉네임",
    "link_zalgo_text": "할로윈 폰트 (잘고)",
    "link_text_repeater": "텍스트 도배기",
    "link_small_text": "작은 글씨체",
    "link_bold_text": "영어 굵은 글씨체",
    "link_morse_code": "모스 부호 번역기",
    "link_cursive_text": "영어 필기체 변환기",
    "link_upside_down_text": "거꾸로 글씨체",
    "link_vaporwave_text": "감성 폰트 (Vaporwave)",
    "link_bubble_text": "동그라미 폰트 (Bubble)",
    "link_gothic_text": "고딕 글씨체",
    "link_heart_symbols": "하트 특수문자",
    "link_star_symbols": "별 특수문자",
    "link_aesthetic_symbols": "감성 특수문자",
    "link_arrow_symbols": "화살표 특수문자",
    "link_flower_symbols": "꽃 특수문자",
    "link_check_marks": "체크 표시",
    "link_emoji_faces": "이모지 페이스",
    "link_math_symbols": "수학 기호",
    "link_japanese_symbols": "일본 특수문자",
    "link_korean_symbols": "한글 특수문자",
    "link_music_symbols": "음표 특수문자",
    "link_cross_symbols": "십자가 특수문자",
    "link_about_us": "회사 소개",
    "link_contact_us": "문의하기",
    "link_authors_team": "작성자 및 팀",
    "link_editorial_guidelines": "편집 가이드라인",
    "link_sitemap": "사이트맵",
    "link_privacy_policy": "개인정보처리방침",
    "link_terms_of_service": "이용약관"
  },
  ms: {
    "title_navigation": "NAVIGASI",
    "title_symbols_for": "SIMBOL UNTUK",
    "title_text_tools": "ALAT TEKS",
    "title_trending_now": "TRENDING SEKARANG",
    "title_all_categories": "SEMUA KATEGORI",
    "title_generators": "Generator",
    "title_top_categories": "Kategori Utama",
    "title_discover": "Teroka",
    "title_company": "Syarikat",
    "link_instagram_symbols": "Simbol Instagram",
    "link_discord_symbols": "Simbol Discord",
    "link_tiktok_symbols": "Simbol TikTok",
    "link_roblox_symbols": "Simbol Roblox",
    "link_bio_generator": "Generator Bio",
    "link_username_generator": "Generator Nama Pengguna",
    "link_character_counter": "Penghitung Aksara",
    "link_strikethrough_text": "Teks Dicoret",
    "link_emoticons": "Emotikon & Kaomoji",
    "link_invisible_character": "Aksara Tidak Kelihatan",
    "link_blank_space": "Ruang Kosong",
    "link_bullet_points": "Mata Bulat",
    "link_free_fire_names": "Nama Free Fire",
    "link_zalgo_text": "Teks Zalgo",
    "link_text_repeater": "Pengulang Teks",
    "link_small_text": "Teks Kecil",
    "link_bold_text": "Teks Tebal",
    "link_morse_code": "Kod Morse",
    "link_cursive_text": "Teks Kursif",
    "link_upside_down_text": "Teks Terbalik",
    "link_vaporwave_text": "Teks Vaporwave",
    "link_bubble_text": "Teks Buih",
    "link_gothic_text": "Teks Gotik",
    "link_heart_symbols": "Simbol Hati",
    "link_star_symbols": "Simbol Bintang",
    "link_aesthetic_symbols": "Simbol Estetik",
    "link_arrow_symbols": "Simbol Anak Panah",
    "link_flower_symbols": "Simbol Bunga",
    "link_check_marks": "Tanda Tanda",
    "link_emoji_faces": "Muka Emoji",
    "link_math_symbols": "Simbol Matematik",
    "link_japanese_symbols": "Simbol Jepun",
    "link_korean_symbols": "Simbol Korea",
    "link_music_symbols": "Simbol Muzik",
    "link_cross_symbols": "Simbol Salib",
    "link_about_us": "Tentang Kami",
    "link_contact_us": "Hubungi Kami",
    "link_authors_team": "Penulis & Pasukan",
    "link_editorial_guidelines": "Garis Panduan Editorial",
    "link_sitemap": "Peta Laman",
    "link_privacy_policy": "Dasar Privasi",
    "link_terms_of_service": "Syarat Perkhidmatan"
  },
  pl: {
    "title_navigation": "NAWIGACJA",
    "title_symbols_for": "SYMBOLE DLA",
    "title_text_tools": "NARZĘDZIA TEKSTOWE",
    "title_trending_now": "TERAZ POPULARNE",
    "title_all_categories": "WSZYSTKIE KATEGORIE",
    "title_generators": "Generatory",
    "title_top_categories": "Najważniejsze Kategorie",
    "title_discover": "Odkrywaj",
    "title_company": "Firma",
    "link_instagram_symbols": "Symbole na Instagram",
    "link_discord_symbols": "Symbole na Discord",
    "link_tiktok_symbols": "Symbole na TikTok",
    "link_roblox_symbols": "Symbole do Roblox",
    "link_bio_generator": "Generator Bio",
    "link_username_generator": "Generator Nazw Użytkownika",
    "link_character_counter": "Licznik Znaków",
    "link_strikethrough_text": "Tekst Przekreślony",
    "link_emoticons": "Emotikony i Kaomoji",
    "link_invisible_character": "Niewidzialny Znak",
    "link_blank_space": "Puste Miejsce",
    "link_bullet_points": "Punktory",
    "link_free_fire_names": "Nazwy do Free Fire",
    "link_zalgo_text": "Tekst Zalgo",
    "link_text_repeater": "Powtarzacz Tekstu",
    "link_small_text": "Mały Tekst",
    "link_bold_text": "Pogrubiony Tekst",
    "link_morse_code": "Kod Morse'a",
    "link_cursive_text": "Tekst Pisany (Kursywa)",
    "link_upside_down_text": "Tekst do Góry Nogami",
    "link_vaporwave_text": "Tekst Vaporwave",
    "link_bubble_text": "Tekst w Bąbelkach",
    "link_gothic_text": "Tekst Gotycki",
    "link_heart_symbols": "Symbole Serca",
    "link_star_symbols": "Symbole Gwiazd",
    "link_aesthetic_symbols": "Symbole Estetyczne",
    "link_arrow_symbols": "Symbole Strzałek",
    "link_flower_symbols": "Symbole Kwiatów",
    "link_check_marks": "Znaczniki Wyboru",
    "link_emoji_faces": "Twarze Emoji",
    "link_math_symbols": "Symbole Matematyczne",
    "link_japanese_symbols": "Symbole Japońskie",
    "link_korean_symbols": "Symbole Koreańskie",
    "link_music_symbols": "Symbole Muzyczne",
    "link_cross_symbols": "Symbole Krzyża",
    "link_about_us": "O Nas",
    "link_contact_us": "Kontakt",
    "link_authors_team": "Autorzy i Zespół",
    "link_editorial_guidelines": "Wytyczne Redakcyjne",
    "link_sitemap": "Mapa Strony",
    "link_privacy_policy": "Polityka Prywatności",
    "link_terms_of_service": "Regulamin"
  },
  pt: {
    "title_navigation": "NAVEGAÇÃO",
    "title_symbols_for": "SÍMBOLOS PARA",
    "title_text_tools": "FERRAMENTAS DE TEXTO",
    "title_trending_now": "TENDÊNCIAS AGORA",
    "title_all_categories": "TODAS AS CATEGORIAS",
    "title_generators": "Geradores",
    "title_top_categories": "Principais Categorias",
    "title_discover": "Descobrir",
    "title_company": "Empresa",
    "link_instagram_symbols": "Símbolos para Instagram",
    "link_discord_symbols": "Símbolos para Discord",
    "link_tiktok_symbols": "Símbolos para TikTok",
    "link_roblox_symbols": "Símbolos para Roblox",
    "link_bio_generator": "Gerador de Bio",
    "link_username_generator": "Gerador de Nome de Usuário",
    "link_character_counter": "Contador de Caracteres",
    "link_strikethrough_text": "Texto Tachado",
    "link_emoticons": "Emoticons e Kaomoji",
    "link_invisible_character": "Caractere Invisível",
    "link_blank_space": "Espaço em Branco",
    "link_bullet_points": "Marcadores",
    "link_free_fire_names": "Nomes para Free Fire",
    "link_zalgo_text": "Texto Zalgo",
    "link_text_repeater": "Repetidor de Texto",
    "link_small_text": "Texto Pequeno",
    "link_bold_text": "Texto em Negrito",
    "link_morse_code": "Código Morse",
    "link_cursive_text": "Texto Cursivo",
    "link_upside_down_text": "Texto de Cabeça para Baixo",
    "link_vaporwave_text": "Texto Vaporwave",
    "link_bubble_text": "Texto em Balão",
    "link_gothic_text": "Texto Gótico",
    "link_heart_symbols": "Símbolos de Coração",
    "link_star_symbols": "Símbolos de Estrela",
    "link_aesthetic_symbols": "Símbolos Estéticos",
    "link_arrow_symbols": "Símbolos de Seta",
    "link_flower_symbols": "Símbolos de Flor",
    "link_check_marks": "Marcas de Seleção",
    "link_emoji_faces": "Caras de Emoji",
    "link_math_symbols": "Símbolos Matemáticos",
    "link_japanese_symbols": "Símbolos Japoneses",
    "link_korean_symbols": "Símbolos Coreanos",
    "link_music_symbols": "Símbolos de Música",
    "link_cross_symbols": "Símbolos de Cruz",
    "link_about_us": "Sobre Nós",
    "link_contact_us": "Contate-nos",
    "link_authors_team": "Autores e Equipe",
    "link_editorial_guidelines": "Diretrizes Editoriais",
    "link_sitemap": "Mapa do Site",
    "link_privacy_policy": "Política de Privacidade",
    "link_terms_of_service": "Termos de Serviço"
  },
  ru: {
    "title_navigation": "НАВИГАЦИЯ",
    "title_symbols_for": "СИМВОЛЫ ДЛЯ",
    "title_text_tools": "ИНСТРУМЕНТЫ ДЛЯ ТЕКСТА",
    "title_trending_now": "ПОПУЛЯРНОЕ СЕЙЧАС",
    "title_all_categories": "ВСЕ КАТЕГОРИИ",
    "title_generators": "Генераторы",
    "title_top_categories": "Популярные Категории",
    "title_discover": "Узнать Больше",
    "title_company": "Компания",
    "link_instagram_symbols": "Символы для Instagram",
    "link_discord_symbols": "Символы для Discord",
    "link_tiktok_symbols": "Символы для TikTok",
    "link_roblox_symbols": "Символы для Roblox",
    "link_bio_generator": "Генератор Био",
    "link_username_generator": "Генератор Никнеймов",
    "link_character_counter": "Счетчик Символов",
    "link_strikethrough_text": "Зачеркнутый Текст",
    "link_emoticons": "Смайлы и Каомодзи",
    "link_invisible_character": "Невидимый Символ",
    "link_blank_space": "Пустой Пробел",
    "link_bullet_points": "Маркеры Списка",
    "link_free_fire_names": "Ники для Free Fire",
    "link_zalgo_text": "Залго Текст",
    "link_text_repeater": "Повторитель Текста",
    "link_small_text": "Мелкий Шрифт",
    "link_bold_text": "Жирный Шрифт",
    "link_morse_code": "Азбука Морзе",
    "link_cursive_text": "Прописной Шрифт",
    "link_upside_down_text": "Перевернутый Текст",
    "link_vaporwave_text": "Вейпорвейв Текст",
    "link_bubble_text": "Текст в Кружочках",
    "link_gothic_text": "Готический Шрифт",
    "link_heart_symbols": "Символы Сердечек",
    "link_star_symbols": "Символы Звезд",
    "link_aesthetic_symbols": "Эстетичные Символы",
    "link_arrow_symbols": "Символы Стрелок",
    "link_flower_symbols": "Символы Цветов",
    "link_check_marks": "Значки Галочек",
    "link_emoji_faces": "Эмодзи Лица",
    "link_math_symbols": "Математические Знаки",
    "link_japanese_symbols": "Японские Символы",
    "link_korean_symbols": "Корейские Символы",
    "link_music_symbols": "Музыкальные Ноты",
    "link_cross_symbols": "Символы Креста",
    "link_about_us": "О нас",
    "link_contact_us": "Контакты",
    "link_authors_team": "Авторы и Команда",
    "link_editorial_guidelines": "Редакционная Политика",
    "link_sitemap": "Карта Сайта",
    "link_privacy_policy": "Политика Конфиденциальности",
    "link_terms_of_service": "Условия Использования"
  },
  sv: {
    "title_navigation": "NAVIGERING",
    "title_symbols_for": "SYMBOLER FÖR",
    "title_text_tools": "TEXTVERKTYG",
    "title_trending_now": "TRENDAR JUST NU",
    "title_all_categories": "ALLA KATEGORIER",
    "title_generators": "Generatorer",
    "title_top_categories": "Toppkategorier",
    "title_discover": "Upptäck",
    "title_company": "Företag",
    "link_instagram_symbols": "Instagram Symboler",
    "link_discord_symbols": "Discord Symboler",
    "link_tiktok_symbols": "TikTok Symboler",
    "link_roblox_symbols": "Roblox Symboler",
    "link_bio_generator": "Bio Generator",
    "link_username_generator": "Användarnamnsgenerator",
    "link_character_counter": "Teckenräknare",
    "link_strikethrough_text": "Genomstruken Text",
    "link_emoticons": "Emoticons & Kaomoji",
    "link_invisible_character": "Osynligt Tecken",
    "link_blank_space": "Blanksteg",
    "link_bullet_points": "Punktlistor",
    "link_free_fire_names": "Free Fire Namn",
    "link_zalgo_text": "Zalgo Text",
    "link_text_repeater": "Textupprepare",
    "link_small_text": "Liten Text",
    "link_bold_text": "Fet Text",
    "link_morse_code": "Morse kod",
    "link_cursive_text": "Kursiv Text",
    "link_upside_down_text": "Upp och Ner Text",
    "link_vaporwave_text": "Vaporwave Text",
    "link_bubble_text": "Bubbeltext",
    "link_gothic_text": "Gotisk Text",
    "link_heart_symbols": "Hjärtsymboler",
    "link_star_symbols": "Stjärnsymboler",
    "link_aesthetic_symbols": "Estetiska Symboler",
    "link_arrow_symbols": "Pilsymboler",
    "link_flower_symbols": "Blomsymboler",
    "link_check_marks": "Bockar",
    "link_emoji_faces": "Emoji Ansikten",
    "link_math_symbols": "Matte Symboler",
    "link_japanese_symbols": "Japanska Symboler",
    "link_korean_symbols": "Koreanska Symboler",
    "link_music_symbols": "Musik Symboler",
    "link_cross_symbols": "Kors Symboler",
    "link_about_us": "Om Oss",
    "link_contact_us": "Kontakta Oss",
    "link_authors_team": "Författare & Team",
    "link_editorial_guidelines": "Redaktionella Riktlinjer",
    "link_sitemap": "Sajtanalys (Sitemap)",
    "link_privacy_policy": "Integritetspolicy",
    "link_terms_of_service": "Användarvillkor"
  },
  tr: {
    "title_navigation": "NAVİGASYON",
    "title_symbols_for": "İÇİN SEMBOLLER",
    "title_text_tools": "METİN ARAÇLARI",
    "title_trending_now": "ŞU ANDA POPÜLER",
    "title_all_categories": "TÜM KATEGORİLER",
    "title_generators": "Şekilli Yazıcılar",
    "title_top_categories": "Popüler Kategoriler",
    "title_discover": "Keşfet",
    "title_company": "Şirket",
    "link_instagram_symbols": "Instagram Sembolleri",
    "link_discord_symbols": "Discord Sembolleri",
    "link_tiktok_symbols": "TikTok Sembolleri",
    "link_roblox_symbols": "Roblox Sembolleri",
    "link_bio_generator": "Biyografi Oluşturucu",
    "link_username_generator": "Kullanıcı Adı Oluşturucu",
    "link_character_counter": "Karakter Sayıcı",
    "link_strikethrough_text": "Üstü Çizili Yazı",
    "link_emoticons": "İfadeler & Kaomoji",
    "link_invisible_character": "Görünmez Harf",
    "link_blank_space": "Boşluk Kopyalama",
    "link_bullet_points": "Madde İşaretleri",
    "link_free_fire_names": "Free Fire Şekilli İsimler",
    "link_zalgo_text": "Zalgo Yazı",
    "link_text_repeater": "Metin Yineleyici",
    "link_small_text": "Küçük Yazı",
    "link_bold_text": "Kalın Yazı",
    "link_morse_code": "Mors Alfabesi",
    "link_cursive_text": "El Yazısı",
    "link_upside_down_text": "Ters Yazı",
    "link_vaporwave_text": "Vaporwave Metin",
    "link_bubble_text": "Balonlu Yazı",
    "link_gothic_text": "Gotik Yazı",
    "link_heart_symbols": "Kalp Sembolleri",
    "link_star_symbols": "Yıldız Sembolleri",
    "link_aesthetic_symbols": "Estetik Semboller",
    "link_arrow_symbols": "Ok Sembolleri",
    "link_flower_symbols": "Çiçek Sembolleri",
    "link_check_marks": "Onay İşaretleri",
    "link_emoji_faces": "Emoji Yüzleri",
    "link_math_symbols": "Matematik Sembolleri",
    "link_japanese_symbols": "Japonca Semboller",
    "link_korean_symbols": "Korece Semboller",
    "link_music_symbols": "Müzik Notaları",
    "link_cross_symbols": "Haç Sembolleri",
    "link_about_us": "Hakkımızda",
    "link_contact_us": "İletişim",
    "link_authors_team": "Yazarlar & Ekip",
    "link_editorial_guidelines": "Yayın İlkeleri",
    "link_sitemap": "Site Haritası",
    "link_privacy_policy": "Gizlilik Politikası",
    "link_terms_of_service": "Kullanım Koşulları"
  }
};

for (const [lang, translations] of Object.entries(langData)) {
  const filePath = path.join(translationsDir, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    try {
      const fileContent = fs.readFileSync(filePath, 'utf8');
      const data = JSON.parse(fileContent);
      const merged = { ...data, ...translations };
      fs.writeFileSync(filePath, JSON.stringify(merged, null, 2), 'utf8');
      console.log(`Successfully updated ${lang}.json`);
    } catch (e) {
      console.error(`Error updating ${lang}.json:`, e);
    }
  } else {
    console.warn(`Translation file for ${lang} does not exist.`);
  }
}
